#!/bin/bash

CONTAINER_NAME=$1

docker run -d --name $CONTAINER_NAME --restart always \
  -v /srv/gitlab-runner/$CONTAINER_NAME/config:/etc/gitlab-runner \
  -v /var/run/docker.sock:/var/run/docker.sock \
  gitlab/gitlab-runner:latest